apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-mfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-mfe
  template:
    metadata:
      labels:
        app: customer-management-mfe
    spec:
      containers:
      - name: customer-management-mfe
        image: srikanth8/customer-management-mfe:latest
        env:
        - name: BACKEND_URL
          value: "http://customer-management-mfe-service.default.svc.cluster.local:80"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-mfe-service
spec:
  selector:
    app: customer-management-mfe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
